### ISSUE TITLE
Request: We need file directory for sponsors thumbnail image

### ISSUE THREAD

**Issue by Seo-yul** [golangkorea/gophercon-korea-web#4]
issue:
I am working on the sponsor page now. This page uses the sponsor's logo and thumbnail images.
but, there is currently no directory for this.

Where should I save it?

URL:
https://github.com/golangkorea/gophercon-korea-2023/tree/main/public/images

suggestion:
`public/images/sponsors/thumbnail/<SPONSORS_NAME>_thumbnail.<type>`

or

`public/images/sponsors/<grade>/<SPONSORS_NAME>_thumbnail.<type>`

**Comment by paikend** [comment]
`
public/images/sponsors/thumbnail/<SPONSORS_NAME>_thumbnail.<type>
`
`
public/images/sponsors/thumbnails/<SPONSORS_NAME>_thumbnail.<type>
`
이렇게하면 더 restful할 것 같아요. :) 

grade로 하면 하위 디렉토리가  diamonds, golds, silvers, bronzes, communities 등 여러 개로 나뉘네요. 설계에 필요한 내용이 아니라면 "복잡한 것 보다 단순한 것이 좋다." 이유로 위에 의견이 좋습니다!
그리고 grade 디렉토리에는 썸네일 말고 다른 것도 들어갈 수 있을 것 같아서 현재 기준으로는 네이밍이 모호할 수 있을 것 같아요.

postfix로 _thumbnail이 붙는데, 디렉토리와 네이밍이 겹치는게 있어서 _logo 로 끝나거나 가로세로 사이즈 들어가도 괜찮을 것 같아요.
(리사이징 있으면 디렉토리 경로로 표시하면 더 좋을 것 같아요. 근데 랜딩 이미지라 필요는 없을 것 같아요.)
잘 모르지만 도움이 되길바라며 코멘트 남깁니다.

**Comment by Seo-yul** [comment]
> `public/images/sponsors/thumbnail/<SPONSORS_NAME>_thumbnail.<type>` `public/images/sponsors/thumbnails/<SPONSORS_NAME>_thumbnail.<type>` 이렇게하면 더 restful할 것 같아요. :)
> 
> grade로 하면 하위 디렉토리가 diamonds, golds, silvers, bronzes, communities 등 여러 개로 나뉘네요. 설계에 필요한 내용이 아니라면 "복잡한 것 보다 단순한 것이 좋다." 이유로 위에 의견이 좋습니다! 그리고 grade 디렉토리에는 썸네일 말고 다른 것도 들어갈 수 있을 것 같아서 현재 기준으로는 네이밍이 모호할 수 있을 것 같아요.
> 
> postfix로 _thumbnail이 붙는데, 디렉토리와 네이밍이 겹치는게 있어서 _logo 로 끝나거나 가로세로 사이즈 들어가도 괜찮을 것 같아요. (리사이징 있으면 디렉토리 경로로 표시하면 더 좋을 것 같아요. 근데 랜딩 이미지라 필요는 없을 것 같아요.) 잘 모르지만 도움이 되길바라며 코멘트 남깁니다.

의견 감사합니다.
현재 각 기업이름으로 이미 로고가 저장되어있고 등급별로 디렉토리 구조가 정해진것이 있어서 해당 부분 수정시 이미 작성된 코드를 리펙토링 해야하는 공수가 발생할거라 생각됩니다 XD..

이미 머리가 많이 아프시겠지만 고려 부탁드립니다. @ChanghyeonYoon 
다른 분들도 많은 조언 부탁드립니다.

**Comment by ChanghyeonYoon** [comment]
grade로 나눠 둔 이유는 아직 스폰서가 확정이 되지 않은상태고 이미지들도 기업으로부터 직접 받은것이 아닌 제가 직접 인터넷에서 주워온거라 지금의 구조로 되어있습니다! 스폰서가 확정되고 기업에서 로고를 받으면 말씀해주신대로 변경해도 괜찮을 것 같아요!
어짜피 이미지 다 새로 넣어야 하니까요!

**Comment by Seo-yul** [comment]
> grade로 나눠 둔 이유는 아직 스폰서가 확정이 되지 않은상태고 이미지들도 기업으로부터 직접 받은것이 아닌 제가 직접 인터넷에서 주워온거라 지금의 구조로 되어있습니다! 스폰서가 확정되고 기업에서 로고를 받으면 말씀해주신대로 변경해도 괜찮을 것 같아요! 어짜피 이미지 다 새로 넣어야 하니까요!

(로고 등) 디렉토리 구조 확정하여 짜 넣어주시면 팔로우해서 스폰서 카드 쪽 진행 하겠습니다

**Comment by ChanghyeonYoon** [comment]
pending
