### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by ChanghyeonYoon** [golangkorea/gophercon-korea-web#5]
- [x] SEO
- [x] i18n @hrh858 #3
- [x] 위치 클립보드 복사 기능
- [x] 일정 추가 기능 (Add to Calendar)
- [x] Main Section 동영상 수정 + 카운트다운, 행사정보 추가 
- [x] Q&A
- [ ] 타국 GopherCon Ref 추가
- [x] Contact - Open KakaoTalk
- [x] #9
- [x] #6
- [x] COC 탭 (파트별로)
- [x] 행사문의 탭

**Comment by ChanghyeonYoon** [comment]
Can you check the `/program/1` page? The top nav menus are not showing up. @hrh858

**Comment by hrh858** [comment]
> Can you check the `/program/1` page? The top nav menus are not showing up. @hrh858

Check the following pull request! :)
https://github.com/golangkorea/gophercon-korea-2023/pull/12
