### ISSUE TITLE
프로그램 탭 @jeonsoh

### ISSUE THREAD

**Issue by ChanghyeonYoon** [golangkorea/gophercon-korea-web#9]

**Comment by ChanghyeonYoon** [comment]
이미지 수정 부탁드려요!

**Comment by jeonsoh** [comment]
- [x] 프로그램 탭 > 디테일 뷰 > 연관 프로그램 소개 시 random1, random2 값이 같지 않도록 수정 
- [x] 이미지가 없는 speaker의 경우 default image 추가
       (+ 이미지가 없는 speaker의 경우 프로그램 탭 > 디테일 뷰 > 연관 프로그램 소개 시  배경이 하얀색이어서 글씨가 보이지 않는 문제 수정 )
- [x] main > about cardview처럼 round rectangle 적용

**Comment by ChanghyeonYoon** [comment]
프로그램 상세 페이지에서  하단 추천 프로그램의 이미지 크기가 변하는 이슈가 있는데 확인 부탁드립니당! @jeonsoh

**Comment by jeonsoh** [comment]
이미지 height를 제한하면 길이가 긴 이미지가 위아래로 압축된?것처럼 보이고, 제한하지 않으면 상대적으로 길이가 작은 이미지의 하단에 빈공간이 보이네요 
- 높이가 작은 이미지를 높이가 긴 이미지의 height에 맞게 위아래로 늘려서 배치(늘어나보임) 
- 높이가 작은 이미지를 이미지 사이즈 상관없이 위아래 빈공간을 두고 가운데 정렬 
- 이미지 height에 특정 높이 제한 (긴 이미지가 위아래로 눌려보임)

어떤 방법이 좋을까요?

**Comment by ChanghyeonYoon** [comment]
@jeonsoh resizeMode를 사용해서 하면될듯합니다!
